version: '3.9'
services:
  api-gateway-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${WEBPORT:-8080}:8080"
    restart: always
    profiles:
      - all
    depends_on:
      - postgres
    environment:
      ONTOPORTAL_APIKEY: "put here APIKEY"
      SPRING_DATASOURCE_URL: jdbc:postgresql://0.0.0.0:5432/db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: backend
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=developer
    ports:
      - "5432:5432"
    networks:
      - network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - network
networks:
  network:
    driver: bridge
