version: '3.9'
services:
  api-gateway-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${WEBPORT:-8080}:8080"
    profiles:
      - all
    depends_on:
      - postgres
    environment:
      ONTOPORTAL_APIKEY: "put here APIKEY"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: none

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=developer
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
