#webserver
server.servlet.context-path=/api-gateway/
# caching
spring.cache.type=simple
# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

# Authentification
jwt.secret=${JWT_SECRET:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
jwt.expiration=86400000

user.admin.password=${ADMIN_PASSWORD:change_me}
spring.codec.max-in-memory-size=100MB

oidc.client-id=${OIDC_CLIENT_ID:https://terminology.services.base4nfdi.de}
oidc.client-secret=${OIDC_CLIENT_SECRET:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
oidc.authority=${OIDC_AUTHORITY:https://infraproxy.nfdi-aai.dfn.de}
oidc.authorization-endpoint=${OIDC_AUTHORIZATION_ENDPOINT:https://infraproxy.nfdi-aai.dfn.de/idp/profile/oidc/authorize}
oidc.token-endpoint=${OIDC_TOKEN_ENDPOINT:https://infraproxy.nfdi-aai.dfn.de/idp/profile/oidc/token}
oidc.userinfo-endpoint=${OIDC_USERINFO_ENDPOINT:https://infraproxy.nfdi-aai.dfn.de/idp/profile/oidc/userinfo}
oidc.end-session-endpoint=${OIDC_END_SESSION_ENDPOINT:https://infraproxy.nfdi-aai.dfn.de/idp/profile/Logout}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${OIDC_ISSUER:https://infraproxy.nfdi-aai.dfn.de}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OIDC_JWK_SET_URI:https://infraproxy.nfdi-aai.dfn.de/idp/profile/oidc/keyset}