CREATE TABLE terminology_collection
(
    id          UUID   NOT NULL,
    user_id     BIGINT NOT NULL,
    description VARCHAR(500),
    label       VARCHAR(255),
    CONSTRAINT pk_terminologycollection PRIMARY KEY (id)
);

CREATE TABLE terminology_collection_terminologies
(
    terminology_collection_id UUID NOT NULL,
    terminologies             VARCHAR(255)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    roles   VARCHAR(255)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE terminology_collection
    ADD CONSTRAINT FK_TERMINOLOGYCOLLECTION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE terminology_collection_terminologies
    ADD CONSTRAINT fk_terminologycollectionterminologies_on_terminologycollection FOREIGN KEY (terminology_collection_id) REFERENCES terminology_collection (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);