-- Create CollectionCollaborator join table with roles for collaborators
CREATE SEQUENCE IF NOT EXISTS collection_collaborator_seq START WITH 1 INCREMENT BY 50;
CREATE TABLE collection_collaborator
(

    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    collection_id     UUID NOT NULL,
    user_id           BIGINT NOT NULL,
    role             VARCHAR(50) NOT NULL,
    CONSTRAINT pk_collection_collaborator PRIMARY KEY (id)
);

ALTER TABLE collection_collaborator
    ADD CONSTRAINT fk_collection_collaborator_on_collection FOREIGN KEY (collection_id) REFERENCES terminology_collection (id);

ALTER TABLE collection_collaborator
    ADD CONSTRAINT fk_collection_collaborator_on_user FOREIGN KEY (user_id) REFERENCES users (id);

